"""add field lokasi_kampus at table user form

Revision ID: 2c9f71d1192a
Revises: 7834eed33548
Create Date: 2025-02-14 01:09:58.916767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9f71d1192a'
down_revision = '7834eed33548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lokasi_kampus', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_form', schema=None) as batch_op:
        batch_op.drop_column('lokasi_kampus')

    # ### end Alembic commands ###
