"""rename field pas foto

Revision ID: 387fc74699e2
Revises: 8ed7fcfd458a
Create Date: 2025-02-13 20:20:57.922112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387fc74699e2'
down_revision = '8ed7fcfd458a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pas_foto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pas_foto_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('pas_foto', sa.String(), nullable=False))
        batch_op.drop_column('pass_foto_id')
        batch_op.drop_column('pass_foto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pas_foto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pass_foto', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pass_foto_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('pas_foto')
        batch_op.drop_column('pas_foto_id')

    # ### end Alembic commands ###
