"""remove field created_at from table user form data

Revision ID: 670df82b3818
Revises: 2c9f71d1192a
Create Date: 2025-02-14 01:12:36.251278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670df82b3818'
down_revision = '2c9f71d1192a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_certificate', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user_cv', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user_krs', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user_ktm', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user_pas_foto', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user_rangkuman_nilai', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_rangkuman_nilai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('user_pas_foto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('user_ktm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('user_krs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('user_cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('user_certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
