"""add field jurusan

Revision ID: 7834eed33548
Revises: 387fc74699e2
Create Date: 2025-02-14 01:06:07.280239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7834eed33548'
down_revision = '387fc74699e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jurusan', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_form', schema=None) as batch_op:
        batch_op.drop_column('jurusan')

    # ### end Alembic commands ###
