"""rename database pas foto

Revision ID: 8ed7fcfd458a
Revises: d474636278e8
Create Date: 2025-02-13 20:19:38.589697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed7fcfd458a'
down_revision = 'd474636278e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_pass_foto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pass_foto',
    sa.Column('pass_foto_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pass_foto', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_form.user_id'], name='user_pass_foto_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pass_foto_id', name='user_pass_foto_pkey')
    )
    # ### end Alembic commands ###
