"""update models user_form

Revision ID: aa476f7c0fff
Revises: 
Create Date: 2025-02-16 17:04:20.855463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa476f7c0fff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_form', schema=None) as batch_op:
        batch_op.drop_constraint('user_form_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_form', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_form_user_id_key', ['user_id'])

    # ### end Alembic commands ###
