"""change rangkuman_id to rangkuman_nilai_id from UserRangkumanNilaiModel

Revision ID: b4f9051f45d7
Revises: 
Create Date: 2025-02-17 00:35:41.035135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f9051f45d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_rangkuman_nilai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rangkuman_nilai_id', sa.String(), nullable=False))
        batch_op.drop_column('rangkuman_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_rangkuman_nilai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rangkuman_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('rangkuman_nilai_id')

    # ### end Alembic commands ###
